---

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache-vhosts_filename }}"
    owner: root
    group: root
    mode: 0664
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlinks in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache-vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites_enabled/{{ apache-vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/00-default.conf"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost