Vagrant.configure("2") do |config|
    config.vm.box = "dummy"
    config.vm.provider :proxmox do |proxmox|
      proxmox.endpoint = 'https://proxmox-server:8006/api2/json'
      proxmox.user_name = 'root@pam'
      proxmox.password = 'your_password'
      proxmox.vm_type = :lxc
      proxmox.os_template = 'local:vztmpl/debian-10-standard_10.0-1_amd64.tar.gz'
      proxmox.pool_name = 'mypool'
      proxmox.storage_pool = 'local-lvm'
      proxmox.node_name = 'proxmox-node'
      proxmox.vm_id_range = 900..910
    end
  
    (1..3).each do |i|
      config.vm.define "container#{i}" do |container|
        container.vm.provider :proxmox do |proxmox|
          proxmox.vm_id = 900 + i
          proxmox.hostname = "container#{i}"
          proxmox.memory = 512
          proxmox.cores = 1
          proxmox.network_interfaces = [{
            name: 'eth0',
            bridge: 'vmbr0',
            ip_address: "192.168.1.#{50 + i}/24",
            gateway: '192.168.1.1'
          }]
        end
  
        container.vm.provision :ansible do |ansible|
          ansible.playbook = "playbook.yml"
          ansible.extra_vars = {
            container_name: "container#{i}"
          }
        end
      end
    end
  end
  