# Create user cloud-init files
# NOTE: The storage used fort these files has to support sinppets
---
- name: Create user cloud-init files
  template:
    src: user_template.j2
    dest: '{{snippets_path}}{{item.vmid}}-user.yml'
    owner: root
    group: root
    mode: 0644
  loop: '{{computers}}'
  when: 'item.state == "new"'
  no_log: yes
